//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string LName { get; set; }
        public string FName { get; set; }
        public string Phone { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Inv_ID { get; set; }
        public string Drivers_License { get; set; }
        public Nullable<System.DateTime> RentalDate { get; set; }
    }
}
