//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public string Confirmation_ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CarSize { get; set; }
        public string Time { get; set; }
    
        public virtual CarSize CarSize1 { get; set; }
    }
}
