//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class CarSize
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarSize()
        {
            this.Reservations = new HashSet<Reservation>();
            // this.Vehicles = new HashSet<Vehicle>();
            this.Vehicles = new ObservableCollection<Vehicle>();
        }
    
        public string Size { get; set; }
        public string SizeCode { get; set; }
        public Nullable<double> DailyRate { get; set; }
        public Nullable<double> MileageRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Vehicle> Vehicles { get; set; }
    }
}
