//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public string Inv_ID { get; set; }
        public string Manuf_Name { get; set; }
        public string Model { get; set; }
        public string CarSize { get; set; }
    
        public virtual CarSize CarSize1 { get; set; }
    }
}
